// flow-typed signature: 833b148bb4447c6ae4455a7d3e356d7c
// flow-typed version: <<STUB>>/clipped-preset-webpack-nodejs_v^0.1.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipped-preset-webpack-nodejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipped-preset-webpack-nodejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipped-preset-webpack-nodejs/clipped.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipped-preset-webpack-nodejs/clipped.config.js' {
  declare module.exports: $Exports<'clipped-preset-webpack-nodejs/clipped.config'>;
}
