// flow-typed signature: 369a27b4db9bcb374a0af8e127b85c0c
// flow-typed version: <<STUB>>/codacy-coverage_v^2.0.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codacy-coverage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codacy-coverage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codacy-coverage/bin/codacy-coverage' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/coverageParser' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/getGitData' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/handleInput' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/impl/lcov' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/logger' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/reporter' {
  declare module.exports: any;
}

declare module 'codacy-coverage/lib/util' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/cli' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/coverageParser' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/getGitData' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/handleInput' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/handleMultiLangInput' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/helper' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/lcov' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/lcov2' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/logger' {
  declare module.exports: any;
}

declare module 'codacy-coverage/test/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codacy-coverage/bin/codacy-coverage.js' {
  declare module.exports: $Exports<'codacy-coverage/bin/codacy-coverage'>;
}
declare module 'codacy-coverage/index' {
  declare module.exports: $Exports<'codacy-coverage'>;
}
declare module 'codacy-coverage/index.js' {
  declare module.exports: $Exports<'codacy-coverage'>;
}
declare module 'codacy-coverage/lib/coverageParser.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/coverageParser'>;
}
declare module 'codacy-coverage/lib/getGitData.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/getGitData'>;
}
declare module 'codacy-coverage/lib/handleInput.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/handleInput'>;
}
declare module 'codacy-coverage/lib/impl/lcov.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/impl/lcov'>;
}
declare module 'codacy-coverage/lib/logger.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/logger'>;
}
declare module 'codacy-coverage/lib/reporter.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/reporter'>;
}
declare module 'codacy-coverage/lib/util.js' {
  declare module.exports: $Exports<'codacy-coverage/lib/util'>;
}
declare module 'codacy-coverage/test/cli.js' {
  declare module.exports: $Exports<'codacy-coverage/test/cli'>;
}
declare module 'codacy-coverage/test/coverageParser.js' {
  declare module.exports: $Exports<'codacy-coverage/test/coverageParser'>;
}
declare module 'codacy-coverage/test/getGitData.js' {
  declare module.exports: $Exports<'codacy-coverage/test/getGitData'>;
}
declare module 'codacy-coverage/test/handleInput.js' {
  declare module.exports: $Exports<'codacy-coverage/test/handleInput'>;
}
declare module 'codacy-coverage/test/handleMultiLangInput.js' {
  declare module.exports: $Exports<'codacy-coverage/test/handleMultiLangInput'>;
}
declare module 'codacy-coverage/test/helper.js' {
  declare module.exports: $Exports<'codacy-coverage/test/helper'>;
}
declare module 'codacy-coverage/test/lcov.js' {
  declare module.exports: $Exports<'codacy-coverage/test/lcov'>;
}
declare module 'codacy-coverage/test/lcov2.js' {
  declare module.exports: $Exports<'codacy-coverage/test/lcov2'>;
}
declare module 'codacy-coverage/test/logger.js' {
  declare module.exports: $Exports<'codacy-coverage/test/logger'>;
}
declare module 'codacy-coverage/test/reporter.js' {
  declare module.exports: $Exports<'codacy-coverage/test/reporter'>;
}
