// flow-typed signature: 91105b487f6731287d96eef907659ecf
// flow-typed version: <<STUB>>/dargs_v^5.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dargs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dargs/index' {
  declare module.exports: $Exports<'dargs'>;
}
declare module 'dargs/index.js' {
  declare module.exports: $Exports<'dargs'>;
}
