// flow-typed signature: 817b29db074117e098fb9a49f69b8fa4
// flow-typed version: <<STUB>>/eslint-config-standard-flow_v^1.0.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-standard-flow/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-standard-flow/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-standard-flow/index' {
  declare module.exports: $Exports<'eslint-config-standard-flow'>;
}
declare module 'eslint-config-standard-flow/index.js' {
  declare module.exports: $Exports<'eslint-config-standard-flow'>;
}
declare module 'eslint-config-standard-flow/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-standard-flow/test/basic'>;
}
declare module 'eslint-config-standard-flow/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-standard-flow/test/validate-config'>;
}
