// flow-typed signature: bedd7005eec404bccbb2d4678daddc65
// flow-typed version: <<STUB>>/extends-classes_v^1.0.5/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extends-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extends-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extends-classes/lib/extends-classes' {
  declare module.exports: any;
}

declare module 'extends-classes/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extends-classes/index' {
  declare module.exports: $Exports<'extends-classes'>;
}
declare module 'extends-classes/index.js' {
  declare module.exports: $Exports<'extends-classes'>;
}
declare module 'extends-classes/lib/extends-classes.js' {
  declare module.exports: $Exports<'extends-classes/lib/extends-classes'>;
}
declare module 'extends-classes/test/index.js' {
  declare module.exports: $Exports<'extends-classes/test/index'>;
}
