// flow-typed signature: e7be6171b4b34f5daf9086851d773808
// flow-typed version: <<STUB>>/generator-clipped-base_v^0.1.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generator-clipped-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generator-clipped-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generator-clipped-base/generators/app/index' {
  declare module.exports: any;
}

declare module 'generator-clipped-base/generators/app/templates/_clipped.config' {
  declare module.exports: any;
}

declare module 'generator-clipped-base/generators/app/templates/src/_index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generator-clipped-base/generators/app/index.js' {
  declare module.exports: $Exports<'generator-clipped-base/generators/app/index'>;
}
declare module 'generator-clipped-base/generators/app/templates/_clipped.config.js' {
  declare module.exports: $Exports<'generator-clipped-base/generators/app/templates/_clipped.config'>;
}
declare module 'generator-clipped-base/generators/app/templates/src/_index.js' {
  declare module.exports: $Exports<'generator-clipped-base/generators/app/templates/src/_index'>;
}
