// flow-typed signature: 4ad401965c4cf7d289417deb9d2efddb
// flow-typed version: <<STUB>>/git-url-parse_v^7.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-url-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-url-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-url-parse/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-url-parse/lib/index.js' {
  declare module.exports: $Exports<'git-url-parse/lib/index'>;
}
