// flow-typed signature: d848e514a70110f0e6a192a33fca88b7
// flow-typed version: <<STUB>>/jointed_v1.5.6/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jointed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jointed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jointed/src/chains/chainable' {
  declare module.exports: any;
}

declare module 'jointed/src/index' {
  declare module.exports: any;
}

declare module 'jointed/src/primitives/KeyArray' {
  declare module.exports: any;
}

declare module 'jointed/src/primitives/ObjectMap' {
  declare module.exports: any;
}

declare module 'jointed/src/primitives/ParamConstructor' {
  declare module.exports: any;
}

declare module 'jointed/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jointed/src/chains/chainable.js' {
  declare module.exports: $Exports<'jointed/src/chains/chainable'>;
}
declare module 'jointed/src/index.js' {
  declare module.exports: $Exports<'jointed/src/index'>;
}
declare module 'jointed/src/primitives/KeyArray.js' {
  declare module.exports: $Exports<'jointed/src/primitives/KeyArray'>;
}
declare module 'jointed/src/primitives/ObjectMap.js' {
  declare module.exports: $Exports<'jointed/src/primitives/ObjectMap'>;
}
declare module 'jointed/src/primitives/ParamConstructor.js' {
  declare module.exports: $Exports<'jointed/src/primitives/ParamConstructor'>;
}
declare module 'jointed/src/utils/index.js' {
  declare module.exports: $Exports<'jointed/src/utils/index'>;
}
