// flow-typed signature: b526d6f5f4e05ea5399c1412fbd0c6b3
// flow-typed version: <<STUB>>/mem-fs_v^1.1.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mem-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mem-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mem-fs/index' {
  declare module.exports: $Exports<'mem-fs'>;
}
declare module 'mem-fs/index.js' {
  declare module.exports: $Exports<'mem-fs'>;
}
