// flow-typed signature: 59429704627c5196ec21245c4c08cb41
// flow-typed version: <<STUB>>/mem-fs-editor_v^3.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mem-fs-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mem-fs-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mem-fs-editor/lib/actions/append' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/commit' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/copy-tpl' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/copy' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/delete' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/exists' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/extend-json' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/move' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/read-json' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/read' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/write-json' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/actions/write' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/index' {
  declare module.exports: any;
}

declare module 'mem-fs-editor/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mem-fs-editor/lib/actions/append.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/append'>;
}
declare module 'mem-fs-editor/lib/actions/commit.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/commit'>;
}
declare module 'mem-fs-editor/lib/actions/copy-tpl.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/copy-tpl'>;
}
declare module 'mem-fs-editor/lib/actions/copy.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/copy'>;
}
declare module 'mem-fs-editor/lib/actions/delete.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/delete'>;
}
declare module 'mem-fs-editor/lib/actions/exists.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/exists'>;
}
declare module 'mem-fs-editor/lib/actions/extend-json.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/extend-json'>;
}
declare module 'mem-fs-editor/lib/actions/move.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/move'>;
}
declare module 'mem-fs-editor/lib/actions/read-json.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/read-json'>;
}
declare module 'mem-fs-editor/lib/actions/read.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/read'>;
}
declare module 'mem-fs-editor/lib/actions/write-json.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/write-json'>;
}
declare module 'mem-fs-editor/lib/actions/write.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/actions/write'>;
}
declare module 'mem-fs-editor/lib/index.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/index'>;
}
declare module 'mem-fs-editor/lib/util.js' {
  declare module.exports: $Exports<'mem-fs-editor/lib/util'>;
}
