// flow-typed signature: 6ca58ecad11437b7faa0f3cd22693298
// flow-typed version: <<STUB>>/yeoman-environment_v^2.0.5/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yeoman-environment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yeoman-environment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yeoman-environment/lib/adapter' {
  declare module.exports: any;
}

declare module 'yeoman-environment/lib/environment' {
  declare module.exports: any;
}

declare module 'yeoman-environment/lib/resolver' {
  declare module.exports: any;
}

declare module 'yeoman-environment/lib/store' {
  declare module.exports: any;
}

declare module 'yeoman-environment/lib/util/log' {
  declare module.exports: any;
}

declare module 'yeoman-environment/lib/util/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yeoman-environment/lib/adapter.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/adapter'>;
}
declare module 'yeoman-environment/lib/environment.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/environment'>;
}
declare module 'yeoman-environment/lib/resolver.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/resolver'>;
}
declare module 'yeoman-environment/lib/store.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/store'>;
}
declare module 'yeoman-environment/lib/util/log.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/util/log'>;
}
declare module 'yeoman-environment/lib/util/util.js' {
  declare module.exports: $Exports<'yeoman-environment/lib/util/util'>;
}
