// flow-typed signature: 6a1030d18b194432b82f44774ebc9325
// flow-typed version: <<STUB>>/dockerode_v^2.5.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dockerode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dockerode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dockerode/lib/config' {
  declare module.exports: any;
}

declare module 'dockerode/lib/container' {
  declare module.exports: any;
}

declare module 'dockerode/lib/docker' {
  declare module.exports: any;
}

declare module 'dockerode/lib/exec' {
  declare module.exports: any;
}

declare module 'dockerode/lib/image' {
  declare module.exports: any;
}

declare module 'dockerode/lib/network' {
  declare module.exports: any;
}

declare module 'dockerode/lib/node' {
  declare module.exports: any;
}

declare module 'dockerode/lib/plugin' {
  declare module.exports: any;
}

declare module 'dockerode/lib/secret' {
  declare module.exports: any;
}

declare module 'dockerode/lib/service' {
  declare module.exports: any;
}

declare module 'dockerode/lib/task' {
  declare module.exports: any;
}

declare module 'dockerode/lib/util' {
  declare module.exports: any;
}

declare module 'dockerode/lib/volume' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dockerode/lib/config.js' {
  declare module.exports: $Exports<'dockerode/lib/config'>;
}
declare module 'dockerode/lib/container.js' {
  declare module.exports: $Exports<'dockerode/lib/container'>;
}
declare module 'dockerode/lib/docker.js' {
  declare module.exports: $Exports<'dockerode/lib/docker'>;
}
declare module 'dockerode/lib/exec.js' {
  declare module.exports: $Exports<'dockerode/lib/exec'>;
}
declare module 'dockerode/lib/image.js' {
  declare module.exports: $Exports<'dockerode/lib/image'>;
}
declare module 'dockerode/lib/network.js' {
  declare module.exports: $Exports<'dockerode/lib/network'>;
}
declare module 'dockerode/lib/node.js' {
  declare module.exports: $Exports<'dockerode/lib/node'>;
}
declare module 'dockerode/lib/plugin.js' {
  declare module.exports: $Exports<'dockerode/lib/plugin'>;
}
declare module 'dockerode/lib/secret.js' {
  declare module.exports: $Exports<'dockerode/lib/secret'>;
}
declare module 'dockerode/lib/service.js' {
  declare module.exports: $Exports<'dockerode/lib/service'>;
}
declare module 'dockerode/lib/task.js' {
  declare module.exports: $Exports<'dockerode/lib/task'>;
}
declare module 'dockerode/lib/util.js' {
  declare module.exports: $Exports<'dockerode/lib/util'>;
}
declare module 'dockerode/lib/volume.js' {
  declare module.exports: $Exports<'dockerode/lib/volume'>;
}
