// flow-typed signature: c1250f720beb30c926abc66cf3e7a46b
// flow-typed version: <<STUB>>/graceful-ncp_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graceful-ncp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graceful-ncp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'graceful-ncp/index' {
  declare module.exports: $Exports<'graceful-ncp'>;
}
declare module 'graceful-ncp/index.js' {
  declare module.exports: $Exports<'graceful-ncp'>;
}
