// flow-typed signature: 2714b637ab35a6c7281b9e86ad431e3a
// flow-typed version: <<STUB>>/grappling-hook_v^3.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grappling-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grappling-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grappling-hook/Gruntfile' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/errorHandling-async.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/errorHandling-base' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/errorHandling-sync.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/errorHandling-thenables.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/examples.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/fixtures/console' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/fixtures/date' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/fixtures/factories' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/fixtures/index' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#addHooks.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#addSyncHooks.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#addThenableHooks.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#allowHooks.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#callHook.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#callSyncHook.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#callThenableHook.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#getMiddleware.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#hasMiddleware.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#hook.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#hookable.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#pre.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/GrapplingHook#unhook.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/module.attach.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/module.create.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/module.get-set.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/module.mixin.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/options-createThenable.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/options-qualifiers.spec' {
  declare module.exports: any;
}

declare module 'grappling-hook/tests/options-strict.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grappling-hook/Gruntfile.js' {
  declare module.exports: $Exports<'grappling-hook/Gruntfile'>;
}
declare module 'grappling-hook/index' {
  declare module.exports: $Exports<'grappling-hook'>;
}
declare module 'grappling-hook/index.js' {
  declare module.exports: $Exports<'grappling-hook'>;
}
declare module 'grappling-hook/tests/errorHandling-async.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/errorHandling-async.spec'>;
}
declare module 'grappling-hook/tests/errorHandling-base.js' {
  declare module.exports: $Exports<'grappling-hook/tests/errorHandling-base'>;
}
declare module 'grappling-hook/tests/errorHandling-sync.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/errorHandling-sync.spec'>;
}
declare module 'grappling-hook/tests/errorHandling-thenables.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/errorHandling-thenables.spec'>;
}
declare module 'grappling-hook/tests/examples.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/examples.spec'>;
}
declare module 'grappling-hook/tests/fixtures/console.js' {
  declare module.exports: $Exports<'grappling-hook/tests/fixtures/console'>;
}
declare module 'grappling-hook/tests/fixtures/date.js' {
  declare module.exports: $Exports<'grappling-hook/tests/fixtures/date'>;
}
declare module 'grappling-hook/tests/fixtures/factories.js' {
  declare module.exports: $Exports<'grappling-hook/tests/fixtures/factories'>;
}
declare module 'grappling-hook/tests/fixtures/index.js' {
  declare module.exports: $Exports<'grappling-hook/tests/fixtures/index'>;
}
declare module 'grappling-hook/tests/GrapplingHook#addHooks.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#addHooks.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#addSyncHooks.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#addSyncHooks.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#addThenableHooks.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#addThenableHooks.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#allowHooks.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#allowHooks.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#callHook.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#callHook.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#callSyncHook.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#callSyncHook.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#callThenableHook.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#callThenableHook.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#getMiddleware.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#getMiddleware.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#hasMiddleware.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#hasMiddleware.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#hook.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#hook.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#hookable.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#hookable.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#pre.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#pre.spec'>;
}
declare module 'grappling-hook/tests/GrapplingHook#unhook.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/GrapplingHook#unhook.spec'>;
}
declare module 'grappling-hook/tests/module.attach.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/module.attach.spec'>;
}
declare module 'grappling-hook/tests/module.create.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/module.create.spec'>;
}
declare module 'grappling-hook/tests/module.get-set.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/module.get-set.spec'>;
}
declare module 'grappling-hook/tests/module.mixin.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/module.mixin.spec'>;
}
declare module 'grappling-hook/tests/options-createThenable.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/options-createThenable.spec'>;
}
declare module 'grappling-hook/tests/options-qualifiers.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/options-qualifiers.spec'>;
}
declare module 'grappling-hook/tests/options-strict.spec.js' {
  declare module.exports: $Exports<'grappling-hook/tests/options-strict.spec'>;
}
