// flow-typed signature: 9a08831eb2c4ffa967ea1391f8d01e59
// flow-typed version: <<STUB>>/nodegit_v^0.20.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodegit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodegit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodegit/dist/blame' {
  declare module.exports: any;
}

declare module 'nodegit/dist/blob' {
  declare module.exports: any;
}

declare module 'nodegit/dist/branch' {
  declare module.exports: any;
}

declare module 'nodegit/dist/checkout' {
  declare module.exports: any;
}

declare module 'nodegit/dist/cherrypick' {
  declare module.exports: any;
}

declare module 'nodegit/dist/clone' {
  declare module.exports: any;
}

declare module 'nodegit/dist/commit' {
  declare module.exports: any;
}

declare module 'nodegit/dist/config' {
  declare module.exports: any;
}

declare module 'nodegit/dist/convenient_hunks' {
  declare module.exports: any;
}

declare module 'nodegit/dist/convenient_patch' {
  declare module.exports: any;
}

declare module 'nodegit/dist/diff_file' {
  declare module.exports: any;
}

declare module 'nodegit/dist/diff_line' {
  declare module.exports: any;
}

declare module 'nodegit/dist/diff' {
  declare module.exports: any;
}

declare module 'nodegit/dist/enums' {
  declare module.exports: any;
}

declare module 'nodegit/dist/filter_registry' {
  declare module.exports: any;
}

declare module 'nodegit/dist/index' {
  declare module.exports: any;
}

declare module 'nodegit/dist/merge' {
  declare module.exports: any;
}

declare module 'nodegit/dist/nodegit' {
  declare module.exports: any;
}

declare module 'nodegit/dist/note' {
  declare module.exports: any;
}

declare module 'nodegit/dist/object' {
  declare module.exports: any;
}

declare module 'nodegit/dist/odb_object' {
  declare module.exports: any;
}

declare module 'nodegit/dist/odb' {
  declare module.exports: any;
}

declare module 'nodegit/dist/oid' {
  declare module.exports: any;
}

declare module 'nodegit/dist/rebase' {
  declare module.exports: any;
}

declare module 'nodegit/dist/reference' {
  declare module.exports: any;
}

declare module 'nodegit/dist/remote' {
  declare module.exports: any;
}

declare module 'nodegit/dist/repository' {
  declare module.exports: any;
}

declare module 'nodegit/dist/reset' {
  declare module.exports: any;
}

declare module 'nodegit/dist/revert' {
  declare module.exports: any;
}

declare module 'nodegit/dist/revwalk' {
  declare module.exports: any;
}

declare module 'nodegit/dist/signature' {
  declare module.exports: any;
}

declare module 'nodegit/dist/stash' {
  declare module.exports: any;
}

declare module 'nodegit/dist/status_file' {
  declare module.exports: any;
}

declare module 'nodegit/dist/status_list' {
  declare module.exports: any;
}

declare module 'nodegit/dist/status' {
  declare module.exports: any;
}

declare module 'nodegit/dist/submodule' {
  declare module.exports: any;
}

declare module 'nodegit/dist/tag' {
  declare module.exports: any;
}

declare module 'nodegit/dist/tree_entry' {
  declare module.exports: any;
}

declare module 'nodegit/dist/tree' {
  declare module.exports: any;
}

declare module 'nodegit/dist/utils/lookup_wrapper' {
  declare module.exports: any;
}

declare module 'nodegit/dist/utils/normalize_fetch_options' {
  declare module.exports: any;
}

declare module 'nodegit/dist/utils/normalize_options' {
  declare module.exports: any;
}

declare module 'nodegit/dist/utils/shallow_clone' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/clean' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/configureLibssh2' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/install' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/postinstall' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/preinstall' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/submodules/getStatus' {
  declare module.exports: any;
}

declare module 'nodegit/lifecycleScripts/submodules/index' {
  declare module.exports: any;
}

declare module 'nodegit/utils/buildFlags' {
  declare module.exports: any;
}

declare module 'nodegit/utils/execPromise' {
  declare module.exports: any;
}

declare module 'nodegit/utils/gitExecutableLocation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodegit/dist/blame.js' {
  declare module.exports: $Exports<'nodegit/dist/blame'>;
}
declare module 'nodegit/dist/blob.js' {
  declare module.exports: $Exports<'nodegit/dist/blob'>;
}
declare module 'nodegit/dist/branch.js' {
  declare module.exports: $Exports<'nodegit/dist/branch'>;
}
declare module 'nodegit/dist/checkout.js' {
  declare module.exports: $Exports<'nodegit/dist/checkout'>;
}
declare module 'nodegit/dist/cherrypick.js' {
  declare module.exports: $Exports<'nodegit/dist/cherrypick'>;
}
declare module 'nodegit/dist/clone.js' {
  declare module.exports: $Exports<'nodegit/dist/clone'>;
}
declare module 'nodegit/dist/commit.js' {
  declare module.exports: $Exports<'nodegit/dist/commit'>;
}
declare module 'nodegit/dist/config.js' {
  declare module.exports: $Exports<'nodegit/dist/config'>;
}
declare module 'nodegit/dist/convenient_hunks.js' {
  declare module.exports: $Exports<'nodegit/dist/convenient_hunks'>;
}
declare module 'nodegit/dist/convenient_patch.js' {
  declare module.exports: $Exports<'nodegit/dist/convenient_patch'>;
}
declare module 'nodegit/dist/diff_file.js' {
  declare module.exports: $Exports<'nodegit/dist/diff_file'>;
}
declare module 'nodegit/dist/diff_line.js' {
  declare module.exports: $Exports<'nodegit/dist/diff_line'>;
}
declare module 'nodegit/dist/diff.js' {
  declare module.exports: $Exports<'nodegit/dist/diff'>;
}
declare module 'nodegit/dist/enums.js' {
  declare module.exports: $Exports<'nodegit/dist/enums'>;
}
declare module 'nodegit/dist/filter_registry.js' {
  declare module.exports: $Exports<'nodegit/dist/filter_registry'>;
}
declare module 'nodegit/dist/index.js' {
  declare module.exports: $Exports<'nodegit/dist/index'>;
}
declare module 'nodegit/dist/merge.js' {
  declare module.exports: $Exports<'nodegit/dist/merge'>;
}
declare module 'nodegit/dist/nodegit.js' {
  declare module.exports: $Exports<'nodegit/dist/nodegit'>;
}
declare module 'nodegit/dist/note.js' {
  declare module.exports: $Exports<'nodegit/dist/note'>;
}
declare module 'nodegit/dist/object.js' {
  declare module.exports: $Exports<'nodegit/dist/object'>;
}
declare module 'nodegit/dist/odb_object.js' {
  declare module.exports: $Exports<'nodegit/dist/odb_object'>;
}
declare module 'nodegit/dist/odb.js' {
  declare module.exports: $Exports<'nodegit/dist/odb'>;
}
declare module 'nodegit/dist/oid.js' {
  declare module.exports: $Exports<'nodegit/dist/oid'>;
}
declare module 'nodegit/dist/rebase.js' {
  declare module.exports: $Exports<'nodegit/dist/rebase'>;
}
declare module 'nodegit/dist/reference.js' {
  declare module.exports: $Exports<'nodegit/dist/reference'>;
}
declare module 'nodegit/dist/remote.js' {
  declare module.exports: $Exports<'nodegit/dist/remote'>;
}
declare module 'nodegit/dist/repository.js' {
  declare module.exports: $Exports<'nodegit/dist/repository'>;
}
declare module 'nodegit/dist/reset.js' {
  declare module.exports: $Exports<'nodegit/dist/reset'>;
}
declare module 'nodegit/dist/revert.js' {
  declare module.exports: $Exports<'nodegit/dist/revert'>;
}
declare module 'nodegit/dist/revwalk.js' {
  declare module.exports: $Exports<'nodegit/dist/revwalk'>;
}
declare module 'nodegit/dist/signature.js' {
  declare module.exports: $Exports<'nodegit/dist/signature'>;
}
declare module 'nodegit/dist/stash.js' {
  declare module.exports: $Exports<'nodegit/dist/stash'>;
}
declare module 'nodegit/dist/status_file.js' {
  declare module.exports: $Exports<'nodegit/dist/status_file'>;
}
declare module 'nodegit/dist/status_list.js' {
  declare module.exports: $Exports<'nodegit/dist/status_list'>;
}
declare module 'nodegit/dist/status.js' {
  declare module.exports: $Exports<'nodegit/dist/status'>;
}
declare module 'nodegit/dist/submodule.js' {
  declare module.exports: $Exports<'nodegit/dist/submodule'>;
}
declare module 'nodegit/dist/tag.js' {
  declare module.exports: $Exports<'nodegit/dist/tag'>;
}
declare module 'nodegit/dist/tree_entry.js' {
  declare module.exports: $Exports<'nodegit/dist/tree_entry'>;
}
declare module 'nodegit/dist/tree.js' {
  declare module.exports: $Exports<'nodegit/dist/tree'>;
}
declare module 'nodegit/dist/utils/lookup_wrapper.js' {
  declare module.exports: $Exports<'nodegit/dist/utils/lookup_wrapper'>;
}
declare module 'nodegit/dist/utils/normalize_fetch_options.js' {
  declare module.exports: $Exports<'nodegit/dist/utils/normalize_fetch_options'>;
}
declare module 'nodegit/dist/utils/normalize_options.js' {
  declare module.exports: $Exports<'nodegit/dist/utils/normalize_options'>;
}
declare module 'nodegit/dist/utils/shallow_clone.js' {
  declare module.exports: $Exports<'nodegit/dist/utils/shallow_clone'>;
}
declare module 'nodegit/lifecycleScripts/clean.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/clean'>;
}
declare module 'nodegit/lifecycleScripts/configureLibssh2.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/configureLibssh2'>;
}
declare module 'nodegit/lifecycleScripts/install.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/install'>;
}
declare module 'nodegit/lifecycleScripts/postinstall.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/postinstall'>;
}
declare module 'nodegit/lifecycleScripts/preinstall.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/preinstall'>;
}
declare module 'nodegit/lifecycleScripts/submodules/getStatus.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/submodules/getStatus'>;
}
declare module 'nodegit/lifecycleScripts/submodules/index.js' {
  declare module.exports: $Exports<'nodegit/lifecycleScripts/submodules/index'>;
}
declare module 'nodegit/utils/buildFlags.js' {
  declare module.exports: $Exports<'nodegit/utils/buildFlags'>;
}
declare module 'nodegit/utils/execPromise.js' {
  declare module.exports: $Exports<'nodegit/utils/execPromise'>;
}
declare module 'nodegit/utils/gitExecutableLocation.js' {
  declare module.exports: $Exports<'nodegit/utils/gitExecutableLocation'>;
}
