// flow-typed signature: 164b909aeba1643ecb866b55f00949c5
// flow-typed version: <<STUB>>/yarn-install_v^0.5.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-install'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-install' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarn-install/bin/yarn-install' {
  declare module.exports: any;
}

declare module 'yarn-install/bin/yarn-remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarn-install/bin/yarn-install.js' {
  declare module.exports: $Exports<'yarn-install/bin/yarn-install'>;
}
declare module 'yarn-install/bin/yarn-remove.js' {
  declare module.exports: $Exports<'yarn-install/bin/yarn-remove'>;
}
declare module 'yarn-install/index' {
  declare module.exports: $Exports<'yarn-install'>;
}
declare module 'yarn-install/index.js' {
  declare module.exports: $Exports<'yarn-install'>;
}
